Repository bcgov/dormant-site-reclamation-program, pull requests merged in 2021-03, with the labels that each got.

#50 MDS-3536: Fix "Create Work IDs" Trigger Not Running For All Applications
  migrations/sql/V2021.03.03.12.27__update_application_after_insert_work_id_trigger.sql
Labels: 👍 Ready for review, 📜 SQL

#51 MDS-3558/MDS-3542: Add Item to Supporting Documents List & Update Company Search on Approved Work View
  services/dsrp-api/app/api/application/models/application.py
  services/dsrp-web/src/components/forms/DocumentUploadForm.js
  services/dsrp-web/src/components/pages/ApplicationSuccessPage.js
Labels: 👍 Ready for review, 💻 Frontend, 💾 Backend

#52 MDS-3468: Update Shared Cost Agreement Letter
  services/dsrp-api/app/api/application/models/application.py
  services/dsrp-api/app/templates/shared_cost_agreement.docx
Labels: 👍 Ready for review, 💾 Backend

#53 MDS-3546: Remove validation on approved contracted work amounts
  services/dsrp-api/app/api/contracted_work/resources/contracted_work_payment.py
  services/dsrp-web/src/components/forms/AdminChangeContractedWorkPaymentStatusForm.js
  services/dsrp-web/src/utils/helpers.js
Labels: 👍 Ready for review, 💻 Frontend, 💾 Backend

#54 MDS-3327/MDS-3530: Create Application Amendment Process & Update Final Report Template
  migrations/sql/V2020.06.01.00.00__create_work_info_view.sql
  migrations/sql/V2021.03.08.10.32__add_application_json_backup.sql
  migrations/sql/V2021.03.11.12.45__insert_application_statuses.sql
  services/dsrp-api/app/api/application/models/application.py
  services/dsrp-api/app/api/application/models/application_status_change.py
  services/dsrp-api/app/api/application/resources/application.py
  services/dsrp-api/app/api/application/resources/application_document.py
  services/dsrp-api/app/api/services/document_generator_service.py
  services/dsrp-api/app/templates/shared_cost_agreement_amendment.docx
  services/dsrp-web/src/assets/downloads/Dormant Sites Reclamation Program - Final Report.docx
  services/dsrp-web/src/assets/downloads/Dormant Sites Reclamation Program - Final Report.pdf
  services/dsrp-web/src/components/forms/ApplicationSectionOne.js
  services/dsrp-web/src/components/forms/ApplicationSectionTwo.js
  services/dsrp-web/src/components/forms/DocumentUploadForm.js
  services/dsrp-web/src/components/pages/ApplicationStatusCard.js
  services/dsrp-web/src/components/pages/ViewApplicationStatusPage.js
  services/dsrp-web/src/constants/assets.js
Labels: 👍 Ready for review, 💻 Frontend, 💾 Backend, 📜 SQL

#55 MDS-3603: Changes to Amendment Letters
  services/dsrp-api/app/api/application/models/application.py
  services/dsrp-api/app/templates/shared_cost_agreement_amendment.docx
Labels: 👍 Ready for review, 💾 Backend

#60 MDS-3484: DSRP Company Payment info admin UI to manage address change
  services/dsrp-api/app/__init__.py
  services/dsrp-api/app/api/company_payment_info/models/company_payment_info.py
  services/dsrp-api/app/api/company_payment_info/namespace.py
  services/dsrp-api/app/api/company_payment_info/resources/company_payment_info.py
  services/dsrp-api/app/api/company_payment_info/response_models.py
  services/dsrp-web/src/actionCreators/companyPaymentInfoActionCreator.js
  services/dsrp-web/src/actions/companyPaymentInfoActions.js
  services/dsrp-web/src/components/admin/CompanyPaymentInfoTable.js
  services/dsrp-web/src/components/admin/ManageCompanyPaymentInfo.js
  services/dsrp-web/src/components/forms/AdminEditCompanyPaymentInfoForm.js
  services/dsrp-web/src/components/layout/HeaderDropdown.js
  services/dsrp-web/src/components/modalContent/AdminEditCompanyPaymentInfoModal.js
  services/dsrp-web/src/components/modalContent/config.js
  services/dsrp-web/src/components/pages/ReviewCompanyPaymentInfoPage.js
  services/dsrp-web/src/constants/actionTypes.js
  services/dsrp-web/src/constants/api.js
  services/dsrp-web/src/constants/forms.js
  services/dsrp-web/src/constants/reducerTypes.js
  services/dsrp-web/src/constants/routes.js
  services/dsrp-web/src/reducers.js
  services/dsrp-web/src/reducers/companyPaymentInfoReducer.js
  services/dsrp-web/src/reducers/rootReducer.js
  services/dsrp-web/src/routes/Routes.js
  services/dsrp-web/src/selectors/companyPaymentInfoSelectors.js
Labels: 👍 Ready for review, 💻 Frontend, 💾 Backend

#61 Fix issue with SCAA field and calculating estimated cost
  services/dsrp-api/app/templates/shared_cost_agreement_amendment.docx
  services/dsrp-web/src/selectors/applicationSelectors.js
Labels: 👍 Ready for review, 💾 Backend
